version: "2.3"
services:
  project:
    image: mos4d
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    runtime: nvidia
    ipc: host
    volumes:
      - ${PWD}/:/mos4d
      - ${DATA}:/mos4d/data
