##Experiments
EXPT:
  ID: "SEKITTI_TRAIN" # Give your logs and model a unique name, the ID should be a string
  MODE: "TRAIN" # "TRAIN", "TEST"

##Data
DATA:
  TRANSFORM: True # If true, the points are pose-aligned before feeding to the model
  POSES: "poses.txt" # Name of the pose file provided in each sequence folder (OPTIONS: FastLIO2 and poses provided by dataset)
  SHUFFLE: True
  NUM_WORKER: 8
  VOXEL_SIZE: 0.1 # Used for discretization in x,y,z when creating a sparse tensor 
  SEMANTIC_CONFIG_FILE: "./config/semantic-kitti-mos.yaml"

##Training
TRAIN:
  DATASET: "SEKITTI" # "SEKITTI", "KITTITRA", "KITTITRA_M", "APOLLO", "NUSC", "WAYMO_M", "AVIA"
  NUM_DEVICES: 4 # could be integer of how many cuda devices to use, or a list that specify which devices to use [0, 1, 2, 3]
  MAX_EPOCH: 60
  LR: 0.0001
  LR_EPOCH: 1
  LR_DECAY: 0.99
  WEIGHT_DECAY: 0.0001
  BATCH_SIZE: 1
  ACC_BATCHES: 1 # accumulate gradients over k batches before stepping into the optimizer
  AUGMENTATION: True

##Prediction
TEST:
  CKPT: "./ckpts/sekitti_60epoch_10scans.ckpt" # path to checkpoint file (.ckpt) to do inference
  NUM_DEVICES: 4
  DATASET: "NUSC" # "SEKITTI", "KITTITRA", "KITTITRA_M", "APOLLO", "NUSC", "WAYMO_M", "AVIA"
  PRED_PATH: "./predictions" # /predictions/ID/confidences(labels)/seq/idx
  STRATEGY: "wo_bayes" # Options: ["non-overlapping", "wo_bayes", "bayes"], do not use non-overlapping, it is super stupid, nobody will do things like this
  BAYES_PRIOR: 0.5 # Moving prior for bayesian fusing
  DELTA_T: 0.1 # Temporal resolution that is used for prediction

##Network
MODEL:
  DELTA_T_PREDICTION: 0.1 # Temporal resolution of scans, nusc: 0.05, kitti: 0.1
  N_PAST_STEPS: 10

# Dataset Config
DATASET:
  SEKITTI:
    PATH: "./data/SeKITTI/sequences" # labeled by PRPonn, seq 00-21
    LIDAR_NAME: "velodyne"
    DELTA_T_DATA: 0.1 # Time between scans in the dataset (0.1s for KITTI)
    TRAIN: [0, 1, 2, 3, 4, 5, 6, 7, 9, 10]
    VAL: [8]
    TEST: [2] # [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  KITTITRA:
    PATH: "./data/KITTITra/sequences" # labeled by PRPonn, seq 19
    LIDAR_NAME: "velodyne"
    TRAIN: [ ]
    VAL: [ ]
    TEST: [19]
  KITTITRA_M:
    PATH: "./data/KITTITra_M/sequences" # labeled by MaRS, seq 00, 01-20
    LIDAR_NAME: "velodyne"
    TRAIN: [ ]
    VAL: [ ]
    TEST: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19] # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  APOLLO: # labeled by PRPonn, seq 00-04
    PATH: "./data/Apollo/sequences"
    LIDAR_NAME: "velodyne"
    TRAIN: [ ]
    VAL: [ ]
    TEST: [2] # [0, 1, 2, 3, 4]
  NUSC: # ours label
    PATH: "/home/mars/MOS_Projects/nuScenes_MOS_Labeling/mini_data"  # or mini_data
    VERSION: "v1.0-mini" # "v1.0-mini"
    TRAIN: "mini_train"  # "train"
    VAL: "mini_val"  # "val"
    TEST: "mini_val"  # "test"
    DELTA_T_DATA: 0.05 # Time between scans in the dataset (0.1s for KITTI)
  WAYMO_M: # labeled by MaRS, seq ?00-43 (NOT ORG IDX)
    PATH: "./data/Waymo_M/sequences"
    LIDAR_NAME: "lidar"
    TRAIN: [ ]
    VAL: [ ]
    TEST: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
           30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]
