##Mode
MODE: "train" # train, finetune, test

##Data
DATA:
  dataset_name: "NUSC" # "SEKITTI", "KITTITRA", "KITTITRA_M", "APOLLO", "NUSC", "WAYMO_M", "AVIA"
  TRANSFORM: True # If true, the points are pose-aligned before feeding to the model
  SHUFFLE: True
  VOXEL_SIZE: 0.2 # Used for discretization in x,y,z when creating a sparse tensor
  N_PAST_STEPS: 10
  DELTA_T_PRED: 0.05 # Temporal resolution of scans, nusc: 0.05, kitti: 0.1

##Training
TRAIN:
  PRETRAIN_METHOD: "4docc"
  pretrain_dataset: "100%nuscenes"
  pretrain_model_name: "vs-0.2_t-3.0_bs-1_epo-60"
  PRETRAIN_MODEL: "pretrain_vs-0.2_t-3.0_bs-1_epo-60_epoch=14.ckpt"
  DATA_PCT: 100   # use 10% of training dataset to train the model
  NUM_DEVICES: 1 # could be integer of how many cuda devices to use, or a list that specify which devices to use [0, 1, 2, 3]
  MAX_EPOCH: 120
  LR: 0.0001
  LR_EPOCH: 1
  LR_DECAY: 0.99
  WEIGHT_DECAY: 0.0001
  BATCH_SIZE: 8
  NUM_WORKERS: 12
  ACC_BATCHES: 1 # accumulate gradients over k batches before stepping into the optimizer
  AUGMENTATION: True
  EGO_MASK: True

# Dataset Config
DATASET:
  SEKITTI:
    PATH: "/home/user/Datasets/SeKITTI/sequences" # labeled by PRPonn, seq 00-21
    SEMANTIC_CONFIG_FILE: "../config/semantic-kitti-mos.yaml"
    POSES: "poses.txt" # Name of the pose file provided in each sequence folder (OPTIONS: FastLIO2 and poses provided by dataset)
    LIDAR_NAME: "velodyne"
    DELTA_T: 0.1 # Time between scans in the dataset (0.1s for KITTI)
    TRAIN: [0, 1, 2, 3, 4, 5, 6, 7, 9, 10]
    VAL: [8]
    TEST: [8]
  KITTITRA:
    PATH: "./data/KITTITra/sequences" # labeled by PRPonn, seq 19
    LIDAR_NAME: "velodyne"
  KITTITRA_M:
    PATH: "./data/KITTITra_M/sequences" # labeled by MaRS, seq 00, 01-20
    LIDAR_NAME: "velodyne"
  APOLLO: # labeled by PRPonn, seq 00-04
    PATH: "./data/Apollo/sequences"
    LIDAR_NAME: "velodyne"
  NUSC: # ours label
    PATH: "/home/user/Datasets/nuScenes"  # /root/autodl-tmp/Datasets/nuScenes /home/user/Datasets/nuScenes
    VERSION: "v1.0-trainval" # "v1.0-mini"
    TRAIN: "train"  # "train"
    VAL: "val"  # "val"
    TEST: "val"  # "test"
    DELTA_T: 0.05 # Time between scans in the dataset
  WAYMO_M: # labeled by MaRS, seq ?00-43 (NOT ORG IDX)
    PATH: "./data/Waymo_M/sequences"
    LIDAR_NAME: "lidar"
